development:
  adapter: postgresql
  encoding: utf8
  database: pair-exchange-development-db
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: pair-exchange-test-db
  pool: 5
  username: 
  password: