development:
  adapter: postgresql
  encoding: unicode
  database: pair_exchange_development
  pool: 5
  username: postgres 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pair_exchange_test
  pool: 5
  username: postgres 
  password:
